apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Test #Nome componente
  description: "Jenkins Job" #Descrition componente
  annotations:
    jenkins.io/job-full-name: 'Folder/Test' #cartella e job jenkins
    jenkins.io/job-url: "https://commissioners-louis-appraisal-pure.trycloudflare.com/job/flogo-deploy-dp/" #url job di jenkins
    sonarqube.org/project-key: 'xxxxxx'
  links:
  - url: https://commissioners-louis-appraisal-pure.trycloudflare.com/ #url di jenkins
    title: Test Jenkins
    icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: group:default/team-dev #owner group che creeremo subito dopo

